spring:
  application:
    name: sistema_comprovantes
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    jdbcUrl: jdbc:mysql://192.168.0.119:3306/MYSPRINGDATA #url para 1 datasource e jdbcUrl para varios
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080
  main:
    allow-bean-definition-overriding: true